backend:
  name: git-gateway
  branch: main

locale: 'pl'
media_folder: content/img
public_folder: content/public

collections:
  - name: "articles"
    label: "Artykuły"
    folder: "content/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Data publikacji", name: "date", widget: "datetime"}
      - {label: "Kolor", name: "color", widget: "color"}
      - {label: "Zdjęcie", name: "photo", widget: "image"}
      - {label: "Treść", name: "body", widget: "markdown"}
      - {label: "Autor", name: "author", widget: "string"}