backend:
  name: git-gateway
  branch: main

locale: 'pl'
media_folder: static/img
public_folder: /img

collections:
  - name: "articles"
    label: "Artykuły"
    folder: "content/article"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Data publikacji", name: "date", widget: "datetime"}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Treść", name: "body", widget: "markdown"}